export GM_REPO_URL="https://gerrit.wikimedia.org/r/path/to/repo"
export GM_REPO_FILE="path/to/file.yaml"
export GM_REPO_BRANCH="master"
export GM_REPO_DIFF="https://gerrit.wikimedia.org/r/plugins/gitiles/"
export GM_SINCE="1 day ago"
export GM_GREP_PAT="pattern1\|pattern2"
export GM_SENDMAIL="/usr/sbin/sendmail"
export GM_MAIL_TO="test@exmaple.com"
export GM_DEBUG=
